apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  selector:
    app: main-app
  ports:
    - name: nginx-http
      port: 80
      targetPort: 80
    - name: multitool-http
      port: 1180
      targetPort: 1180
